### ISSUE TITLE
Model weights on the Hugging Face Hub

### ISSUE THREAD

**Issue by davanstrien** [tzco/VolumeDiffusion#3]
Very cool project! It would be great if the weights for this were also available on the Hugging Face Hub so people can also discover and directly access this work there. Happy to help with that process if it's of interest.

**Comment by tzco** [comment]
Sure! We have uploaded code and models to https://huggingface.co/tzco/VolumeDiffusion. @us if there are anything we missed.

**Comment by davanstrien** [comment]
Awesome, thanks for doing that!!
