### ISSUE TITLE
Could you please provide a complete 100 prompts in text-to-3d evaluation?

### ISSUE THREAD

**Issue by Clear-3d** [tzco/VolumeDiffusion#4]
Hello, thanks for your excellent work! 
In your paper, you mentioned that in the evaluation of text-to-3D, you generated 100 objects and rendered 8 views for each object. However, in Figure 5, 9, 10 in the paper, I can only find 80 prompts. Could you please provide a complete list of prompts? I am currently working on some follow-up research inspired by your work, I also wanna conduct some related tests. If possible, I would greatly appreciate it.

**Comment by tzco** [comment]
Sorry for the late reply. The prompts we used are generated with LLaVA and LLaMA-2 using the computation resources of Microsoft corporation, so it may be a little inconvenient for us to share them here. You can directly use the prompts presented in the paper for follow-up works and comparisons, or you can email me and we will submit an application and go through some compliance reviews and checks :)
